// GENERATED by scripts/online-services.js — do not edit by hand.

// On web, every import of modules/bankAccounts/service resolves here instead
// (metro.config.js). Its synchronous helpers and constants are the real ones;
// each async function runs on the server against the signed-in shop.

import type * as local from '@/modules/bankAccounts/service';
import { rpc } from '@/web/rpc';

export * from '../../modules/bankAccounts/service';

export const createBankAccount: typeof local.createBankAccount = rpc('bankAccounts', 'createBankAccount');
export const listBankAccounts: typeof local.listBankAccounts = rpc('bankAccounts', 'listBankAccounts');
export const getBankAccount: typeof local.getBankAccount = rpc('bankAccounts', 'getBankAccount');
export const updateBankAccount: typeof local.updateBankAccount = rpc('bankAccounts', 'updateBankAccount');
export const deleteBankAccount: typeof local.deleteBankAccount = rpc('bankAccounts', 'deleteBankAccount');
