// GENERATED by scripts/online-services.js — do not edit by hand.

// On web, every import of modules/expenses/service resolves here instead
// (metro.config.js). Its synchronous helpers and constants are the real ones;
// each async function runs on the server against the signed-in shop.

import type * as local from '@/modules/expenses/service';
import { rpc } from '@/web/rpc';

export * from '../../modules/expenses/service';

export const createExpense: typeof local.createExpense = rpc('expenses', 'createExpense');
export const listExpenses: typeof local.listExpenses = rpc('expenses', 'listExpenses');
export const getExpense: typeof local.getExpense = rpc('expenses', 'getExpense');
export const updateExpense: typeof local.updateExpense = rpc('expenses', 'updateExpense');
export const deleteExpense: typeof local.deleteExpense = rpc('expenses', 'deleteExpense');
