// GENERATED by scripts/online-services.js — do not edit by hand.

// On web, every import of modules/invoices/service resolves here instead
// (metro.config.js). Its synchronous helpers and constants are the real ones;
// each async function runs on the server against the signed-in shop.

import type * as local from '@/modules/invoices/service';
import { rpc } from '@/web/rpc';

export * from '../../modules/invoices/service';

export const createInvoice: typeof local.createInvoice = rpc('invoices', 'createInvoice');
export const listInvoices: typeof local.listInvoices = rpc('invoices', 'listInvoices');
export const listInvoicesByParty: typeof local.listInvoicesByParty = rpc('invoices', 'listInvoicesByParty');
export const getInvoice: typeof local.getInvoice = rpc('invoices', 'getInvoice');
export const updateInvoice: typeof local.updateInvoice = rpc('invoices', 'updateInvoice');
export const deleteInvoice: typeof local.deleteInvoice = rpc('invoices', 'deleteInvoice');
export const addInvoiceItem: typeof local.addInvoiceItem = rpc('invoices', 'addInvoiceItem');
export const listInvoiceItems: typeof local.listInvoiceItems = rpc('invoices', 'listInvoiceItems');
export const deleteInvoiceItem: typeof local.deleteInvoiceItem = rpc('invoices', 'deleteInvoiceItem');
export const createInvoiceWithItems: typeof local.createInvoiceWithItems = rpc('invoices', 'createInvoiceWithItems');
export const updateInvoiceWithItems: typeof local.updateInvoiceWithItems = rpc('invoices', 'updateInvoiceWithItems');
export const returnsAgainst: typeof local.returnsAgainst = rpc('invoices', 'returnsAgainst');
export const convertedFrom: typeof local.convertedFrom = rpc('invoices', 'convertedFrom');
export const sourceDocument: typeof local.sourceDocument = rpc('invoices', 'sourceDocument');
export const convertToInvoice: typeof local.convertToInvoice = rpc('invoices', 'convertToInvoice');
export const returnedTotal: typeof local.returnedTotal = rpc('invoices', 'returnedTotal');
export const getInvoiceWithItems: typeof local.getInvoiceWithItems = rpc('invoices', 'getInvoiceWithItems');
export const deleteInvoiceWithItems: typeof local.deleteInvoiceWithItems = rpc('invoices', 'deleteInvoiceWithItems');
export const deletionImpact: typeof local.deletionImpact = rpc('invoices', 'deletionImpact');
export const listInvoicesWithParty: typeof local.listInvoicesWithParty = rpc('invoices', 'listInvoicesWithParty');
