// GENERATED by scripts/online-services.js — do not edit by hand.

// On web, every import of modules/items/service resolves here instead
// (metro.config.js). Its synchronous helpers and constants are the real ones;
// each async function runs on the server against the signed-in shop.

import type * as local from '@/modules/items/service';
import { rpc } from '@/web/rpc';

export * from '../../modules/items/service';

export const createItem: typeof local.createItem = rpc('items', 'createItem');
export const listItems: typeof local.listItems = rpc('items', 'listItems');
export const listCategories: typeof local.listCategories = rpc('items', 'listCategories');
export const getItem: typeof local.getItem = rpc('items', 'getItem');
export const findItemByBarcode: typeof local.findItemByBarcode = rpc('items', 'findItemByBarcode');
export const updateItem: typeof local.updateItem = rpc('items', 'updateItem');
export const deleteItem: typeof local.deleteItem = rpc('items', 'deleteItem');
export const adjustStock: typeof local.adjustStock = rpc('items', 'adjustStock');
