// GENERATED by scripts/online-services.js — do not edit by hand.

// On web, every import of modules/parties/service resolves here instead
// (metro.config.js). Its synchronous helpers and constants are the real ones;
// each async function runs on the server against the signed-in shop.

import type * as local from '@/modules/parties/service';
import { rpc } from '@/web/rpc';

export * from '../../modules/parties/service';

export const getOrCreateWalkInParty: typeof local.getOrCreateWalkInParty = rpc('parties', 'getOrCreateWalkInParty');
export const createParty: typeof local.createParty = rpc('parties', 'createParty');
export const listParties: typeof local.listParties = rpc('parties', 'listParties');
export const getParty: typeof local.getParty = rpc('parties', 'getParty');
export const updateParty: typeof local.updateParty = rpc('parties', 'updateParty');
export const deleteParty: typeof local.deleteParty = rpc('parties', 'deleteParty');
