// GENERATED by scripts/online-services.js — do not edit by hand.

// On web, every import of modules/payments/service resolves here instead
// (metro.config.js). Its synchronous helpers and constants are the real ones;
// each async function runs on the server against the signed-in shop.

import type * as local from '@/modules/payments/service';
import { rpc } from '@/web/rpc';

export * from '../../modules/payments/service';

export const createPayment: typeof local.createPayment = rpc('payments', 'createPayment');
export const listPayments: typeof local.listPayments = rpc('payments', 'listPayments');
export const listPaymentsByParty: typeof local.listPaymentsByParty = rpc('payments', 'listPaymentsByParty');
export const listPaymentsByInvoice: typeof local.listPaymentsByInvoice = rpc('payments', 'listPaymentsByInvoice');
export const getPayment: typeof local.getPayment = rpc('payments', 'getPayment');
export const updatePayment: typeof local.updatePayment = rpc('payments', 'updatePayment');
export const deletePayment: typeof local.deletePayment = rpc('payments', 'deletePayment');
export const netPaidForInvoice: typeof local.netPaidForInvoice = rpc('payments', 'netPaidForInvoice');
export const recomputeInvoiceStatus: typeof local.recomputeInvoiceStatus = rpc('payments', 'recomputeInvoiceStatus');
export const listPaymentsWithParty: typeof local.listPaymentsWithParty = rpc('payments', 'listPaymentsWithParty');
export const recordPayment: typeof local.recordPayment = rpc('payments', 'recordPayment');
