// GENERATED by scripts/online-services.js — do not edit by hand.

// On web, every import of modules/pos/service resolves here instead
// (metro.config.js). Its synchronous helpers and constants are the real ones;
// each async function runs on the server against the signed-in shop.

import type * as local from '@/modules/pos/service';
import { rpc } from '@/web/rpc';

export * from '../../modules/pos/service';

export const createQuickBill: typeof local.createQuickBill = rpc('pos', 'createQuickBill');
