// GENERATED by scripts/online-services.js — do not edit by hand.

// On web, every import of modules/reports/service resolves here instead
// (metro.config.js). Its synchronous helpers and constants are the real ones;
// each async function runs on the server against the signed-in shop.

import type * as local from '@/modules/reports/service';
import { rpc } from '@/web/rpc';

export * from '../../modules/reports/service';

export const salesReport: typeof local.salesReport = rpc('reports', 'salesReport');
export const purchaseReport: typeof local.purchaseReport = rpc('reports', 'purchaseReport');
export const partyOutstanding: typeof local.partyOutstanding = rpc('reports', 'partyOutstanding');
export const stockSummary: typeof local.stockSummary = rpc('reports', 'stockSummary');
export const gstSummary: typeof local.gstSummary = rpc('reports', 'gstSummary');
export const profitReport: typeof local.profitReport = rpc('reports', 'profitReport');
export const itemSalesReport: typeof local.itemSalesReport = rpc('reports', 'itemSalesReport');
export const gstRateBreakup: typeof local.gstRateBreakup = rpc('reports', 'gstRateBreakup');
export const loadGstrInvoices: typeof local.loadGstrInvoices = rpc('reports', 'loadGstrInvoices');
export const gstr1Report: typeof local.gstr1Report = rpc('reports', 'gstr1Report');
export const gstr3bReport: typeof local.gstr3bReport = rpc('reports', 'gstr3bReport');
