// GENERATED by scripts/online-services.js — do not edit by hand.

// On web, every import of modules/settings/service resolves here instead
// (metro.config.js). Its synchronous helpers and constants are the real ones;
// each async function runs on the server against the signed-in shop.

import type * as local from '@/modules/settings/service';
import { rpc } from '@/web/rpc';

export * from '../../modules/settings/service';

export const getSetting: typeof local.getSetting = rpc('settings', 'getSetting');
export const listSettings: typeof local.listSettings = rpc('settings', 'listSettings');
export const setSetting: typeof local.setSetting = rpc('settings', 'setSetting');
export const deleteSetting: typeof local.deleteSetting = rpc('settings', 'deleteSetting');
export const getBusinessProfile: typeof local.getBusinessProfile = rpc('settings', 'getBusinessProfile');
export const getDefaultTaxMode: typeof local.getDefaultTaxMode = rpc('settings', 'getDefaultTaxMode');
export const setDefaultTaxMode: typeof local.setDefaultTaxMode = rpc('settings', 'setDefaultTaxMode');
export const getPrintFormat: typeof local.getPrintFormat = rpc('settings', 'getPrintFormat');
export const setPrintFormat: typeof local.setPrintFormat = rpc('settings', 'setPrintFormat');
export const getVoiceLang: typeof local.getVoiceLang = rpc('settings', 'getVoiceLang');
export const setVoiceLang: typeof local.setVoiceLang = rpc('settings', 'setVoiceLang');
export const getVoiceSpeak: typeof local.getVoiceSpeak = rpc('settings', 'getVoiceSpeak');
export const setVoiceSpeak: typeof local.setVoiceSpeak = rpc('settings', 'setVoiceSpeak');
export const getVoiceOn: typeof local.getVoiceOn = rpc('settings', 'getVoiceOn');
export const setVoiceOn: typeof local.setVoiceOn = rpc('settings', 'setVoiceOn');
