// GENERATED by scripts/online-services.js — do not edit by hand.

// On web, every import of modules/tally/service resolves here instead
// (metro.config.js). Its synchronous helpers and constants are the real ones;
// each async function runs on the server against the signed-in shop.

import type * as local from '@/modules/tally/service';
import { rpc } from '@/web/rpc';

export * from '../../modules/tally/service';

export const loadTallyExport: typeof local.loadTallyExport = rpc('tally', 'loadTallyExport');
export const countLeftOut: typeof local.countLeftOut = rpc('tally', 'countLeftOut');
