// GENERATED by scripts/online-services.js — do not edit by hand.

// The only functions POST /api/rpc/:module/:fn will run. Everything here is an
// exported async function of the app's own service module, executed unchanged
// inside the signed-in shop's transaction (see routes/rpc.ts).

import * as bankAccounts from '@/modules/bankAccounts/service';
import * as expenses from '@/modules/expenses/service';
import * as invoices from '@/modules/invoices/service';
import * as items from '@/modules/items/service';
import * as parties from '@/modules/parties/service';
import * as payments from '@/modules/payments/service';
import * as pos from '@/modules/pos/service';
import * as reports from '@/modules/reports/service';
import * as settings from '@/modules/settings/service';
import * as tally from '@/modules/tally/service';

export type RpcFunction = (...args: any[]) => Promise<unknown>;

export const registry: Record<string, Record<string, RpcFunction>> = {
  bankAccounts: {
    createBankAccount: bankAccounts.createBankAccount,
    listBankAccounts: bankAccounts.listBankAccounts,
    getBankAccount: bankAccounts.getBankAccount,
    updateBankAccount: bankAccounts.updateBankAccount,
    deleteBankAccount: bankAccounts.deleteBankAccount,
  },
  expenses: {
    createExpense: expenses.createExpense,
    listExpenses: expenses.listExpenses,
    getExpense: expenses.getExpense,
    updateExpense: expenses.updateExpense,
    deleteExpense: expenses.deleteExpense,
  },
  invoices: {
    createInvoice: invoices.createInvoice,
    listInvoices: invoices.listInvoices,
    listInvoicesByParty: invoices.listInvoicesByParty,
    getInvoice: invoices.getInvoice,
    updateInvoice: invoices.updateInvoice,
    deleteInvoice: invoices.deleteInvoice,
    addInvoiceItem: invoices.addInvoiceItem,
    listInvoiceItems: invoices.listInvoiceItems,
    deleteInvoiceItem: invoices.deleteInvoiceItem,
    createInvoiceWithItems: invoices.createInvoiceWithItems,
    updateInvoiceWithItems: invoices.updateInvoiceWithItems,
    returnsAgainst: invoices.returnsAgainst,
    convertedFrom: invoices.convertedFrom,
    sourceDocument: invoices.sourceDocument,
    convertToInvoice: invoices.convertToInvoice,
    returnedTotal: invoices.returnedTotal,
    getInvoiceWithItems: invoices.getInvoiceWithItems,
    deleteInvoiceWithItems: invoices.deleteInvoiceWithItems,
    deletionImpact: invoices.deletionImpact,
    listInvoicesWithParty: invoices.listInvoicesWithParty,
  },
  items: {
    createItem: items.createItem,
    listItems: items.listItems,
    listCategories: items.listCategories,
    getItem: items.getItem,
    findItemByBarcode: items.findItemByBarcode,
    updateItem: items.updateItem,
    deleteItem: items.deleteItem,
    adjustStock: items.adjustStock,
  },
  parties: {
    getOrCreateWalkInParty: parties.getOrCreateWalkInParty,
    createParty: parties.createParty,
    listParties: parties.listParties,
    getParty: parties.getParty,
    updateParty: parties.updateParty,
    deleteParty: parties.deleteParty,
  },
  payments: {
    createPayment: payments.createPayment,
    listPayments: payments.listPayments,
    listPaymentsByParty: payments.listPaymentsByParty,
    listPaymentsByInvoice: payments.listPaymentsByInvoice,
    getPayment: payments.getPayment,
    updatePayment: payments.updatePayment,
    deletePayment: payments.deletePayment,
    netPaidForInvoice: payments.netPaidForInvoice,
    recomputeInvoiceStatus: payments.recomputeInvoiceStatus,
    listPaymentsWithParty: payments.listPaymentsWithParty,
    recordPayment: payments.recordPayment,
  },
  pos: {
    createQuickBill: pos.createQuickBill,
  },
  reports: {
    salesReport: reports.salesReport,
    purchaseReport: reports.purchaseReport,
    partyOutstanding: reports.partyOutstanding,
    stockSummary: reports.stockSummary,
    gstSummary: reports.gstSummary,
    profitReport: reports.profitReport,
    itemSalesReport: reports.itemSalesReport,
    gstRateBreakup: reports.gstRateBreakup,
    loadGstrInvoices: reports.loadGstrInvoices,
    gstr1Report: reports.gstr1Report,
    gstr3bReport: reports.gstr3bReport,
  },
  settings: {
    getSetting: settings.getSetting,
    listSettings: settings.listSettings,
    setSetting: settings.setSetting,
    deleteSetting: settings.deleteSetting,
    getBusinessProfile: settings.getBusinessProfile,
    getDefaultTaxMode: settings.getDefaultTaxMode,
    setDefaultTaxMode: settings.setDefaultTaxMode,
    getPrintFormat: settings.getPrintFormat,
    setPrintFormat: settings.setPrintFormat,
    getVoiceLang: settings.getVoiceLang,
    setVoiceLang: settings.setVoiceLang,
    getVoiceSpeak: settings.getVoiceSpeak,
    setVoiceSpeak: settings.setVoiceSpeak,
    getVoiceOn: settings.getVoiceOn,
    setVoiceOn: settings.setVoiceOn,
  },
  tally: {
    loadTallyExport: tally.loadTallyExport,
    countLeftOut: tally.countLeftOut,
  },
};
