// The vendor's Ed25519 PUBLIC key — generated by tools/new-vendor-key.mjs.
//
// This ships inside the APK on purpose. It can verify a licence file and it
// cannot create one, so pulling it out of a decompiled bundle buys an attacker
// nothing. The private half never leaves the vendor's machine.
//
// Regenerating the pair invalidates every licence already issued.
export const VENDOR_PUBLIC_KEY = '31f098192e05a02ef89ec08231ae5715c0f6fcd498472c43bc502e67fc68619a';
