// Preloaded "universal" option lists used by the dropdown (SelectField) inputs.
// These are defaults/presets — most fields still allow a custom typed value.

// All 28 states + 8 union territories of India (for party billing state / GST).
export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

// Common stock/measurement units.
export const ITEM_UNITS = [
  'pcs',
  'kg',
  'g',
  'ltr',
  'ml',
  'mtr',
  'cm',
  'ft',
  'box',
  'dozen',
  'pack',
  'bag',
  'bottle',
  'set',
  'pair',
  'roll',
  'sq ft',
  'unit',
];

// Everyday shop overheads. These are the running costs a small business books
// against the month — they are NOT purchases of stock (those go through a
// purchase invoice so they move inventory and a supplier ledger).
export const EXPENSE_CATEGORIES = [
  'Rent',
  'Salary & Wages',
  'Electricity',
  'Water',
  'Phone & Internet',
  'Transport & Freight',
  'Fuel',
  'Packing Material',
  'Repairs & Maintenance',
  'Printing & Stationery',
  'Advertising',
  'Bank Charges',
  'Professional Fees',
  'Licence & Taxes',
  'Insurance',
  'Tea & Refreshments',
  'Cleaning',
  'Miscellaneous',
];

// Common item categories (custom values allowed on top of these).
export const ITEM_CATEGORIES = [
  'General',
  'Grocery',
  'Electronics',
  'Apparel & Textiles',
  'Hardware',
  'Stationery',
  'Furniture',
  'Cosmetics',
  'Pharmaceuticals',
  'Food & Beverage',
  'Automotive',
  'Services',
  'Raw Material',
  'Other',
];
