import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { listSettings } from '@/modules/settings/service';
import { formatDate, formatMoney, formatQty, formatTaxRate } from '@/utils/format';
import type { InvoiceType } from '@/utils/invoiceNumber';
import type { InvoiceDetail } from '@/modules/invoices/service';

const DOC_LABEL: Record<InvoiceType, string> = {
  sale: 'TAX INVOICE',
  purchase: 'PURCHASE BILL',
  quotation: 'QUOTATION',
  challan: 'DELIVERY CHALLAN',
};

// Business-profile keys (written by the Phase 8 settings screen).
interface BusinessProfile {
  name: string;
  gstin?: string;
  address?: string;
  phone?: string;
}

async function loadProfile(): Promise<BusinessProfile> {
  const rows = await listSettings();
  const map = new Map(rows.map((r) => [r.key, r.value ?? '']));
  return {
    name: map.get('business_name') || 'My Business',
    gstin: map.get('business_gstin') || undefined,
    address: map.get('business_address') || undefined,
    phone: map.get('business_phone') || undefined,
  };
}

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function buildHtml(detail: InvoiceDetail, biz: BusinessProfile): string {
  const { invoice, party, lines } = detail;
  const rows = lines
    .map(
      (l, i) => `
      <tr>
        <td>${i + 1}</td>
        <td>${esc(l.itemName)}</td>
        <td class="num">${formatQty(l.qty)} ${esc(l.itemUnit)}</td>
        <td class="num">${formatMoney(l.rate)}</td>
        <td class="num">${l.taxRate > 0 ? formatTaxRate(l.taxRate) : '-'}</td>
        <td class="num">${formatMoney(l.amount)}</td>
      </tr>`,
    )
    .join('');

  return `<!doctype html><html><head><meta charset="utf-8" />
  <style>
    * { font-family: -apple-system, Roboto, Arial, sans-serif; }
    body { color: #111; padding: 24px; font-size: 13px; }
    .doc { text-align: right; font-size: 20px; font-weight: 700; color: #208AEF; letter-spacing: 1px; }
    .biz { font-size: 20px; font-weight: 700; }
    .muted { color: #666; }
    .row { display: flex; justify-content: space-between; margin-top: 16px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { border-bottom: 1px solid #e5e5e5; padding: 8px 6px; text-align: left; }
    th { background: #f4f8fe; font-size: 11px; text-transform: uppercase; color: #555; }
    .num { text-align: right; }
    .totals { margin-top: 16px; margin-left: auto; width: 260px; }
    .totals div { display: flex; justify-content: space-between; padding: 4px 0; }
    .grand { border-top: 2px solid #111; margin-top: 6px; padding-top: 8px; font-weight: 700; font-size: 15px; }
    .foot { margin-top: 40px; color: #999; font-size: 11px; text-align: center; }
  </style></head><body>
    <div class="doc">${DOC_LABEL[invoice.type]}</div>
    <div class="biz">${esc(biz.name)}</div>
    ${biz.address ? `<div class="muted">${esc(biz.address)}</div>` : ''}
    ${biz.gstin ? `<div class="muted">GSTIN: ${esc(biz.gstin)}</div>` : ''}
    ${biz.phone ? `<div class="muted">${esc(biz.phone)}</div>` : ''}

    <div class="row">
      <div>
        <div class="muted">Bill to</div>
        <div style="font-weight:600">${esc(party?.name ?? '-')}</div>
        ${party?.gstin ? `<div class="muted">GSTIN: ${esc(party.gstin)}</div>` : ''}
        ${party?.phone ? `<div class="muted">${esc(party.phone)}</div>` : ''}
      </div>
      <div style="text-align:right">
        <div><b>${esc(invoice.invoiceNo)}</b></div>
        <div class="muted">${formatDate(invoice.date)}</div>
        <div class="muted">${invoice.paymentStatus.toUpperCase()}</div>
      </div>
    </div>

    <table>
      <thead><tr><th>#</th><th>Item</th><th class="num">Qty</th><th class="num">Rate</th><th class="num">Tax</th><th class="num">Amount</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>

    <div class="totals">
      <div><span>${invoice.taxMode === 'inclusive' ? 'Taxable value' : 'Subtotal'}</span><span>${formatMoney(invoice.subtotal)}</span></div>
      <div><span>${invoice.taxMode === 'inclusive' ? 'GST (included in rate)' : 'Tax'}</span><span>${formatMoney(invoice.taxTotal)}</span></div>
      ${invoice.discount > 0 ? `<div><span>Discount</span><span>- ${formatMoney(invoice.discount)}</span></div>` : ''}
      <div class="grand"><span>Grand total</span><span>${formatMoney(invoice.grandTotal)}</span></div>
    </div>

    <div class="foot">
      ${invoice.taxMode === 'inclusive' ? 'Rates shown are inclusive of GST. · ' : ''}Generated by the billing app · This is a computer-generated document.
    </div>
  </body></html>`;
}

/** Render the invoice to a PDF and open the native share sheet. */
export async function shareInvoicePdf(detail: InvoiceDetail): Promise<void> {
  const biz = await loadProfile();
  const { uri } = await Print.printToFileAsync({ html: buildHtml(detail, biz) });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: detail.invoice.invoiceNo });
  }
}

/**
 * Open the OS print dialog for the invoice (Android print service / AirPrint).
 * From there the user can send it to any connected/Wi-Fi printer or save a PDF —
 * works in Expo Go, no thermal-printer native module needed.
 */
export async function printInvoice(detail: InvoiceDetail): Promise<void> {
  const biz = await loadProfile();
  await Print.printAsync({ html: buildHtml(detail, biz) });
}
