// Re-vendor tools/noble-ed25519.js from the installed @noble/ed25519.
//
//   node tools/vendor-noble.mjs
//
// keygen.html has to run offline from file://, and browsers refuse to load ES
// modules over that scheme — so the library is committed beside it as a plain
// classic script that hangs its exports off window.nobleEd25519. Re-run this
// after upgrading the package; nothing else in the repo depends on the output.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(here, '..', 'node_modules', '@noble', 'ed25519', 'index.js'), 'utf8');

// The library ships one export statement, on its last line, and even says in a
// comment that removing it makes the file usable as a plain script.
const stripped = source.replace(/^export \{[^}]*\};?\s*$/m, '');
if (stripped === source) {
  throw new Error('No export statement found — has @noble/ed25519 changed shape?');
}

const wrapped = `// GENERATED by tools/vendor-noble.mjs — do not edit.
// @noble/ed25519 (MIT, Paul Miller) as a classic script, so keygen.html can use
// it straight from file:// where ES modules are blocked.
(function () {
${stripped}
window.nobleEd25519 = {
  getPublicKeyAsync, signAsync, verifyAsync, utils, hashes, etc,
};
})();
`;

const out = join(here, 'noble-ed25519.js');
writeFileSync(out, wrapped, 'utf8');
console.log(`Wrote ${out}`);
